/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dasi.bench.helper;

/**
 *
 * @author obsidiam
 */
public class QueryConstants {
    final public static String INSTANCE_INFO = "select * from inet_server_addr(), inet_server_port(), pg_backend_pid(), inet_client_addr(), inet_client_port();";
    final public static String CREATE_TEST = "CREATE TABLE test (id  integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, value  float8);";
    final public static String INSERT_TEST = "insert into test(id,value) values(";//just part of a statement, needs ending before querying
    final public static String SELECT_TEST = "select * from test;";
    final public static String UPDATE_SELECT_RAND = "UPDATE test SET value=((SELECT random() * 10 + 1 AS RAND_1_10) * 0.5) WHERE id='";
    final public static String ORDER_BY_TEST = "SELECT id FROM test ORDER BY id ASC;";
    final public static String DELETE_TEST = "delete from test where id=";//just part of a statement, needs ending before querying
    final public static String DROP_TEST = "drop table test;";
}
